### ISSUE TITLE
Redirect to Setup.php

### ISSUE THREAD

**Issue by cixtor** [RandomStorm/DVWA#1]
It would be great a redirection to the file `setup.php` if the installation process was not started. I have this little piece of code checking in the information schema database if the table **users** exists in the database specified in the configuration file.

_Only works with MySQL database_.
```
$ diff login.php login.php.fork 
22a23,31
> 	$users_exists_q = @mysql_query("SELECT table_schema, table_name, create_time
> 		FROM information_schema.tables
> 		WHERE table_schema='{$_DVWA['db_database']}' AND table_name='users'
> 		LIMIT 1");
> 	if( !mysql_fetch_assoc($users_exists_q) ){
> 		header('Location: setup.php');
> 		exit;
> 	}
>
```

**Comment by g0tmi1k** [comment]
Kind of done with 62e52063e5d6f365a54723784a7a709f210296e3 // #37
