### ISSUE TITLE
Catcha - low.php / medium.php

### ISSUE THREAD

**Issue by hansieb** [RandomStorm/DVWA#13]
In low.php (line 7 and 8) and medium.php (line 6 and 7) for the captcha vulnerability, it gets the new password and confirmation of password and assigns these values to variables.

But this only happens for step 1.
In step 2, these two variables $pass_new and $pass_conf are always blank when it is written to the database.

**Comment by g0tmi1k** [comment]
Fixed: 7ca0a06bb109791e93d4424c5e42f25493eeb5e2
