### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by ChrisFernandez** [RandomStorm/DVWA#24]
i unzip the app on a default nginx install on arch linux
getting error 500 when clicking on the setup/reset database :/
php info works... i also followed  this to make sure:
http://hackthistv.com/blog/how-to-install-dvwa-on-ubuntu-server-14-04/

**Comment by digininja** [comment]
Have you checked the nginx error logs?

**Comment by ChrisFernandez** [comment]
yeah nothing other than the 500 error
10.0.x.x - - [14/Mar/2015:08:40:26 +0000] "GET /dvwa/login.php HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36"

**Comment by digininja** [comment]
I don't know nginx, does it not have an error log as well as an access log
like Apache?

**Comment by ChrisFernandez** [comment]
yes i had to enable them. got this:
2015/03/14 09:00:09 [error] 13028#0: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 10.0.x.x, server: localhost, request: "GET / HTTP/1.1", host: "10.0.x.x"

this is my php block

location ~ \.php$ {
                include        fastcgi.conf;
                fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                fastcgi_param  SCRIPT_FILENAME $request_filename;
        }

**Comment by digininja** [comment]
I think you need to add

index index.php;

To that block.

You can also try browsing to the page with index.php explicitly in the URL.

**Comment by ChrisFernandez** [comment]
yeah of course i did try going directly to the index.php have another one called info.php i made that shows the php info and that does work fine.. same directory.. so it is reading php just not this app.
maybe my version of php is not compatible? arch linux usually have the latest of ruby/python/php etc

**Comment by digininja** [comment]
That error message says directory indexing is disabled and you are missing
the index entry which says to me that one problem is the config. If it
still fails when you go to index.php do you get a different error message?

It won't be php version as DVWA has been around for years so will work on
anything that is newer than 5 years old.

**Comment by digininja** [comment]
Quick thought, have you got the php/MySQL library installed and enabled?

**Comment by ChrisFernandez** [comment]
hmm ok you have a point now i dont remember installing the php plugin for mysql.
i just installed php, nginx, mysql

**Comment by digininja** [comment]
Hit the index page directly and check the error message. Fix and repeat
till working.

**Comment by ChrisFernandez** [comment]
ok i find out what was the issue.. will write down solution in case another arch linux and php/mysql person ends up having the same issue. also to note this was in a arm devide, rasperry pi 2.

first I assumed that mysqli.so and mysql.so was uncomented on php.ini but they were not.. so i did this.
extension=mysql.so
extension=mysqli.so
also in the open_basedir the target directory was missing a forward slash /
open_basedir= /srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/
