### ISSUE TITLE
CURL problem showing this

### ISSUE THREAD

**Issue by gbrsec** [RandomStorm/DVWA#25]
-data'create db=create+%2F+Reset+Database' http://127.0.0.1/dvwa/setup.php# --cookie PHPSESSID=1
curl: option --datacreate db=create+%2F+Reset+Database: is unknown
curl: any idea to solve??

**Comment by erwanlr** [comment]
add a space after --data ?

```--data 'create db=create+%2F+Reset+Database' --cookie 'PHPSESSID=1' http://127.0.0.1/dvwa/setup.php```

**Comment by gbrsec** [comment]
ok  it was wrong name dvwa  like this dwva !!lol now is ok can huppend lol!
