### ISSUE TITLE
File upload problem corrected, is there any other solution

### ISSUE THREAD

**Issue by TaimourNazar** [RandomStorm/DVWA#28]
Hi,
Even after giving priviledges to upload folder, we were not able to upload any image file or php file. Then we modified the code and everything started to work fine. Is there any other solution to this? If you are facing similar issue in upload. Just copy and past our code into your low.php file in this directory 
/var/www/dvwa/vulnerabilities/upload/source and everything will work fine.
You might need to modify the $target_path according to your OS

<?php
	if (isset($_POST['Upload'])) {

			$target_path = "/var/www/dvwa/hackable/uploads/";
			$target_path = $target_path . $_FILES['uploaded']['name'];

			if(!move_uploaded_file($_FILES['uploaded']['tmp_name'], $target_path)) {
				
				$html .= '<pre>';
				$html .= 'Your image was not uploaded.';
				$html .= '</pre>';
				echo $target_path." - ";
				echo $_FILES['uploaded']['tmp_name']." - ";
				echo $_FILES['uploaded']['name']." - ";
      		} else {
			
				$html .= '<pre>';
				$html .= ' succesfully uploaded!';
				$html .= '</pre>';
				
			}

		}
?>

**Comment by g0tmi1k** [comment]
Can't say I've had this issue on my setup (Debian 8 x64 & PHP v5.6.12).
What OS are you using _(Linux based by the looks of it!)_? What version of PHP? What user are you logged in as? What folder permission is set on the upload? What user is the web server/php running as?

If you enable `display_errors` in the PHP config (if its not already) - any errors visible?
Anything in the apache logs (access.log & error.log)?
What version of DVWA are you using?
Does it happen on any other level?
What image were you uploading?

**Comment by ethicalhack3r** [comment]
Closing due to lack of response from OP

**Comment by TaimourNazar** [comment]
I think you are using the newer version of DVWA which is 1.9 , It has the corrected code
