### ISSUE TITLE
Captcha: Hidden form

### ISSUE THREAD

**Issue by arall** [RandomStorm/DVWA#29]
Why the captcha form is hidden? 

https://github.com/RandomStorm/DVWA/blob/master/vulnerabilities/captcha/index.php#L35

**Comment by g0tmi1k** [comment]
Fixed: 4d63ffd750776fdbdc59d3e93f876b795322353b

**Comment by g0tmi1k** [comment]
Fixed with : https://github.com/RandomStorm/DVWA/commit/4d63ffd750776fdbdc59d3e93f876b795322353b
