### ISSUE TITLE
Could not connect to the database

### ISSUE THREAD

**Issue by Denuve** [RandomStorm/DVWA#32]
Hi,I followed all instructions and I have read all fixes and I modified the config file hundred times but I still can't connect to the database.
![screenshot from 2015-09-07 10 56 34](https://cloud.githubusercontent.com/assets/10000816/9711891/a8b1403e-554f-11e5-9724-10fc98523b68.png)
![screenshot from 2015-09-07 10 58 26](https://cloud.githubusercontent.com/assets/10000816/9711895/ad796df8-554f-11e5-93b3-b935f287b9c1.png)

**Comment by digininja** [comment]
Can you connect to mysql from the command line with those credentials?

mysql -u admin -ppassword -h 127.0.0.1 -D dvwa

**Comment by Denuve** [comment]
No,I can't.
![screenshot from 2015-09-07 14 21 08](https://cloud.githubusercontent.com/assets/10000816/9715709/b639e85c-556b-11e5-8f44-416a56068cac.png)

**Comment by digininja** [comment]
Remove the space between -p and password, you can't have one there when
providing the password on the command line

**Comment by Denuve** [comment]
![screenshot from 2015-09-07 14 24 09](https://cloud.githubusercontent.com/assets/10000816/9715745/211bc870-556c-11e5-969d-42de28776b60.png)

**Comment by digininja** [comment]
What user did you set up when you installed mysql and what password did you give it? The default user is root not admin, is that where you are going wrong or did you deliberately set up an admin user?

**Comment by Denuve** [comment]
I just changed the default password with 'anna'.The user is root by default.

**Comment by digininja** [comment]
so why are you trying to connect with the username of admin?

**Comment by Denuve** [comment]
I misread something on a post to another fix.Well,I changed the user back to root and here are the results.
![screenshot from 2015-09-07 14 41 16](https://cloud.githubusercontent.com/assets/10000816/9716024/a8b91fec-556e-11e5-8a8a-9b2bd6677b46.png)
![screenshot from 2015-09-07 14 41 20](https://cloud.githubusercontent.com/assets/10000816/9716025/ad096138-556e-11e5-9f72-180dcc168d64.png)
![screenshot from 2015-09-07 14 41 59](https://cloud.githubusercontent.com/assets/10000816/9716027/b0163d7e-556e-11e5-9135-e13868351838.png)

**Comment by digininja** [comment]
You are trying to connect with admin/password but you've said the
credentials are root/anna, have you tried connecting with those?

And from the command line, remove the space between -p and the password
otherwise it will ask you for the password rather than reading it from the
parameter

**Comment by Denuve** [comment]
![screenshot from 2015-09-07 14 49 46](https://cloud.githubusercontent.com/assets/10000816/9716144/b91ebca6-556f-11e5-950e-0e4d6c0dcec8.png)

**Comment by digininja** [comment]
That looks correct, DVWA hasn't managed to set up the database yet. Update
the config file to use the correct credentials then ask it to set up the
database.

An extra bit of advice, I assume you are installing DVWA to learn about web
app vulnerabilities, I'd strongly suggest getting a good grounding in the
full web stack, from the HTML pages down to the database. That way you'll
understand things a lot better when applications throw errors that are
passed up from lower layers such as the database layer.

**Comment by Denuve** [comment]
Thanks for patience and help friend.it's all working now.I have some knowledge about HTML ,MySql and others but i'm just a beginner and i just migrated in linux,and yes,I want to learn about web security and I wish I will become a good ethical hacker one day.Thanks for help again.

**Comment by digininja** [comment]
Glad it's working. Don't neglect the supporting skills, too many people do
and you can tell when you see them testing.

**Comment by manoelitonunes** [comment]
> Thanks for patience and help friend.it's all working now.I have some knowledge about HTML ,MySql and others but i'm just a beginner and i just migrated in linux,and yes,I want to learn about web security and I wish I will become a good ethical hacker one day.Thanks for help again.

Hey can you please help me with the same issue?
How did u manage to get this working?
