### ISSUE TITLE
What is the IP?

### ISSUE THREAD

**Issue by alex36540** [RandomStorm/DVWA#50]
It said in the instructions that the IP of DVWA was http://127.0.0.1/dvwa. Nothing shows up. I put the uncompressed file into the XAMP folder they told me to.

**Comment by g0tmi1k** [comment]
First you need to make sure the web server is running. 
If it is not, why not? What is the OS? What does the logs says?
If it is running, is the the right path to DVWA? What folder did you put it in?

What do you mean by 'nothing shows up'? Does the page 404? white page? forever load? 500 response? 403 error?

**Comment by hackstin** [comment]
how can I know that the web server is running? I'm on kali linux and when I type http://127.0.0.1/dvwa it just goes to  

"Unable to connect

Iceweasel can't establish a connection to the server at 127.0.0.1.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Iceweasel is permitted to access the Web."

**Comment by digininja** [comment]
Look at the process list with:

ps aux

and look for apache or httpd

Check open ports with

netstat -antp

and look for port 80. If you don't understand what either of these are
doing then I recommend taking a step back from looking at web app
vulnerabilities and learn some basic Linux config and operation, it will
make life a lot easier as you progress. Feels like a step back and avoiding
what you are trying to do but without the basics you won't progress very
far.
