### ISSUE TITLE
status in red

### ISSUE THREAD

**Issue by awm1wa** [RandomStorm/DVWA#51]
hi I have a setup problem and  I dont  understand this problem "status in red " please  help 
i use xampp server 3.2.2

![screenshot - 12_2_2015 2_17_23 am](https://cloud.githubusercontent.com/assets/16108366/11516233/7c29d8c0-989b-11e5-9d26-f4a76c75cb32.png)

**Comment by ethicalhack3r** [comment]
It is just telling you that *if* any of the text above was coloured red then there would be issues with some modules. As nothing above is in red on that screenshot then you do not have to worry, just ignore it.

**Comment by awm1wa** [comment]
There were already red, but  I fixed this red. but  now I can't connect the database .. i am checking config file.. and nothing

**Comment by webkodex** [comment]
captcha key missing i added right captcha key from google 


6Lc1hRcTAAAAAI7rDHpXtimKtAYzNrpF_ix893zv
6Lc1hRcTAAAAAM4neJ9K558Uq34C5mQUGxwKKWcS


but its showing in red, is there any way to get rid of this, until i clear this db wanot connect to mysql even with right mysql root pass

**Comment by digininja** [comment]
@webkodex please open your own issue and don't hijack others.

And don't post your private captcha keys in public.
