### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Maigo96** [RandomStorm/DVWA#54]
I can't troubleshoot this issue. I have a status PHP function allow_url_include: Disabled but my php.ini file is set to :on 

Any ideas?
![setup](https://cloud.githubusercontent.com/assets/16862231/12535428/8e388584-c2c6-11e5-9483-49b965d98d9a.PNG)
![ini](https://cloud.githubusercontent.com/assets/16862231/12535429/8f608e8e-c2c6-11e5-820d-5da25a7335f3.PNG)

**Comment by digininja** [comment]
Did you read the comment in the file that says "Doesnt always work"? Have you tried doing this in the main php.ini file?

And have you restarted Apache since you made the change?

**Comment by richardjguy** [comment]
Apache I have restarted but havent been able to find the main php.ini file yet... still looking...

**Comment by digininja** [comment]
Looks like a linix box so

find / -name 'php.ini'

**Comment by richardjguy** [comment]
Owwww... found it it in etc... make sure to change permissions... then it sets up ok

**Comment by digininja** [comment]
A tip, in Linux, the majority of configuration files live in directories in
/etc.

**Comment by richardjguy** [comment]
Thanks... Your help is much appreciated
