### ISSUE TITLE
MySQL PHP library deprecated

### ISSUE THREAD

**Issue by diego-XA** [RandomStorm/DVWA#55]
I've been trying to install DVWA in a Debian 8 server and it looks that it wont connect to the database no matter what.

After some digging I foundthat you are using the "mysql" driver instead of "mysqli". The "mysql" driver is deprecated so it wont work on any modern GNU/linux distribution. (http://php.net/manual/en/function.mysql-connect.php)

Would it be possible to update to "mysqli" so this suite can be used with PHP >= 5.5 ?

Thanks!

**Comment by digininja** [comment]
The change is pretty simple, I've done it on a load of old sites as servers
upgraded.

**Comment by diego-XA** [comment]
Yes, for what I've read it seems that "mysqli" is a straight forward replacement for "mysql" so I guess it should be an easy change.

**Comment by digininja** [comment]
There are a couple of other little things but that is basically it.

**Comment by diego-XA** [comment]
Actually, I've used this and it worked so far.

https://github.com/philip/MySQLConverterTool

**Comment by kocsenc** [comment]
Do we have plans to actually perform this migration? Keeping in mind that these new functions may add security features that may break the app.

**Comment by andymeneely** [comment]
I teach a class at RIT that makes heavy use of DVWA - and this bit us this time. Any progress on this would be much appreciated!! :+1:

**Comment by digininja** [comment]
Changing that won't affect any of the deliberate vulns.

**Comment by diego-XA** [comment]
I used the above tool and it worked. If that solution is suitable for the developers I could commit the changes and send a PR

**Comment by kocsenc** [comment]
Let's try it out @diego-XA ! Thanks.

**Comment by diego-XA** [comment]
I've just sent the PR. Check if everything installs properly. Now it should.
