### ISSUE TITLE
LIVE CD

### ISSUE THREAD

**Issue by r9pasa01** [RandomStorm/DVWA#62]
How to use live CD? Can I use it through USB Flash drive? Does it work if simply copy and paste the contents of the iso file? Does it work in windows?

**Comment by digininja** [comment]
This may be a little harsh but can I suggest that if you do not understand how to use an ISO image then web application testing may also be a little beyond your current skills.

If you do want to continue with this then google iso to usb, there are loads of tools and tutorials.
