### ISSUE TITLE
Medium setting sql injection won't work

### ISSUE THREAD

**Issue by tycho94** [RandomStorm/DVWA#65]
I tried the given solution and numerous solutions available as well as my own.
None of them would give any output or results. Please confirm so this issue can be solved

**Comment by digininja** [comment]
Yes it can be solved using a very basic attack.

**Comment by tycho94** [comment]
Thanks, I'll reconfigure my dvwa and try again. 

Date: Mon, 29 Feb 2016 00:50:48 -0800

**Comment by tycho94** [comment]
>

**Comment by tycho94** [comment]
May I ask you what you filled in? I recreated my dvwa and also tried older versions, where it does work. Odd

**Comment by digininja** [comment]
I'm not showing the answer in an issue as it would spoil it for others. It
is a basic SQLi, nothing special about it, if you are doing anything more
than adding quotes then you are over thinking it.

**Comment by tycho94** [comment]
Exactly my point, I am sure I am doing it correctly as it works in previous versions of dvwa. But it doesn not work in the 1.9 version.

**Comment by digininja** [comment]
I'm running the latest from github and it works fine in that.

**Comment by tycho94** [comment]
http://192.168.20.21/dvwa.new/vulnerabilities/sqli/?id=1&Submit=Submit#

Should this  in medium setting not print the first_name and last_name of the user with ID 1?

**Comment by digininja** [comment]
No
