### ISSUE TITLE
Cannot enable shell_exec

### ISSUE THREAD

**Issue by tomsterley** [RandomStorm/DVWA#73]
I really do not know how to enable shell_exec for command injection, plz help

**Comment by digininja** [comment]
Google is your friend, got these from a simple search:

http://stackoverflow.com/questions/12757891/enable-shell-exec-in-wamp-server

http://blog.tersmitten.nl/how-to-enable-phps-shell_exec-in-centos-5-3.html

**Comment by tomsterley** [comment]
The thing is, I know nothing about PHP, so :/ and Im running dvwa here: tomsterley.com/dvwa

**Comment by digininja** [comment]
First, GET THAT OFF THE INTERNET! It is a deliberately vulnerable app that
is full of holes, do you want your box owned by everyone who reads this
issue list?

Second, the two links have step by step instructions on how to make the
changes

Third, if you don't know php then I'd strongly suggest learning at least
some basic admin skills in the area you are trying to play with before
trying to hack it. It will make your life so much easier. Consider it part
of the learning process.

**Comment by tomsterley** [comment]
I dont really care if someone hacks that database, they cant hack the dvwa login, right?

**Comment by digininja** [comment]
Yes, that is the point, the whole app contains vulnerabilities.

And have you changed ALL the passwords for ALL the accounts? If not then full ownership of the box is literally a login and file upload away.

**Comment by tomsterley** [comment]
Ok, I am taking that down and setting it up on a wamp environment

**Comment by digininja** [comment]
Good idea. Set it up locally and never expose deliberately vulnerable apps to the internet.

**Comment by tomsterley** [comment]
Thanks, Im kind of new to this stuff ;)

**Comment by digininja** [comment]
I hope the fact your site is now returning a 404 is your doing and not someone else

**Comment by tomsterley** [comment]
Its mine.

**Comment by digininja** [comment]
Good, I was slightly worried for you for a while

**Comment by tomsterley** [comment]
Its alright, can someone close this issue now?

**Comment by digininja** [comment]
you can close it yourself, there should be a close button at the end if you are viewing it on Github

**Comment by tomsterley** [comment]
oh.
