### ISSUE TITLE
DVWA cannot connect to database when using MAMP database on Mac

### ISSUE THREAD

**Issue by cardiffsteve** [RandomStorm/DVWA#79]
I have installed DVWA on my Mac and Im using MAMP (instead of XAMPP).
I get the error 'unable to connect to database' when I load DVWA on my browser as shown in pic.
I have looked on various forums and by setting password to blank it appears to fix the problem for xampp, but its not worked for MAMP.  So does DVWA work with MAMP?

The url I browse to using MAMP is: localhost:8888/dvwa

Config file config.inc.php (in applications/MAMP/htdocs/dvwa/config) settings for database:

$_DVWA = array();
$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = '';

![screen shot 2016-05-12 at 18 37 51](https://cloud.githubusercontent.com/assets/6750809/15241715/cca56494-18e9-11e6-9b80-eeb6fa71d1c9.png)

**Comment by cardiffsteve** [comment]
Fixed it, these are the Config file settings you need for MAMP:
$_DVWA = array();
$_DVWA[ 'db_server' ]   = 'localhost';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = 'root';

**Comment by darryllane** [comment]
Are you setting the db password to blank too?

**Comment by cardiffsteve** [comment]
@darryllane  it is set exactly as stated in my previous comment, as 'root' - thanks
