### ISSUE TITLE
command execution always set to impossible 

### ISSUE THREAD

**Issue by AliBawazeEer** [RandomStorm/DVWA#86]
Hi team ,

i have installed DVWA on ubuntu 14 .. 
i am facing issue only in command execution section , the security level always set to impossible however i can set it to low for other challenges . anyone can advise please 

Thank you

**Comment by Kamerabuilt** [comment]
Go to the tab DVWA Security, and set the Security level to "Low". Otherwise, the code will prevent you from doing any code injection with the security level impossible

**Comment by getupandgo** [comment]
Still have this issue.
I've installed  v1.0.7 LiveCD and when executed some shell commands security level ONLY on command injection tab set on "high", while all other tabs had "low" level.
Then i reinstalled DVWA to latest version and had the same issue.

**Comment by digininja** [comment]
I've just tested on a fairly up to date git version and it works fine for me. I know this used to be an issue but can't remember what caused it. Try the git release.
