### ISSUE TITLE
Problems with PHP 5.5

### ISSUE THREAD

**Issue by whinstant** [RandomStorm/DVWA#89]
Hello everybody,

tried to set up dvwa on kali linux with xampp.
Due to using PHP5.5, i get errors connecting the db because the mysql functions like mysql_connect() were not used. Found out, that they are not used in PHP5.5 because they are depricated.
Any issues on how to get dvwa set up?

**Comment by digininja** [comment]
Check my last PR, that version should work in all modern versions of PHP

**Comment by whinstant** [comment]
Thank you for your quick answer. It works very well!

**Comment by digininja** [comment]
Could you please add a comment to the PR just to say it works for you.

Thanks

**Comment by ethicalhack3r** [comment]
Fixed in:
https://github.com/RandomStorm/DVWA/pull/58
https://github.com/RandomStorm/DVWA/pull/58
