### ISSUE TITLE
i cant Database Setup on DVWA help.

### ISSUE THREAD

**Issue by kalasyang42** [RandomStorm/DVWA#90]
i need help guys . my apache2 is running and mysql and i already downloaded the DVWA 1.9 .. i need help guys . thank in Advance..
![screenshot from 2016-07-14 23-53-30](https://cloud.githubusercontent.com/assets/20461841/16846334/8890d8c4-49db-11e6-86ac-f7286e0c1b6c.png)

**Comment by digininja** [comment]
What problem are you having?

**Comment by kalasyang42** [comment]
What i need to do next ? my problem is look i cant create/reset database ... Look on the picture thanks.

**Comment by digininja** [comment]
Have you clicked the button?

**Comment by kalasyang42** [comment]
![8890d8c4-49db-11e6-86ac-f7286e0c1b6c](https://cloud.githubusercontent.com/assets/20461841/16913432/de8ea53c-4d1c-11e6-93bb-20f46c25b110.png)


_______________________

http://prntscr.com/bubmp9

__________________

**Comment by digininja** [comment]
Turn on error displaying or check your error logs to see what is failing.

If you don't know how to do that I'd suggest you learn a bit of web sys
admin before continuing rather than just blindly asking for the
instructions as it will help you loads in the future.
